# Generated by Django 3.2.4 on 2023-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='issue_date',
            field=models.DateTimeField(default=None, verbose_name='Issue date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='issue_date',
            field=models.DateTimeField(default=None, verbose_name='Issue date'),
            preserve_default=False,
        ),
    ]
